Playfield:

<Head>:
    canvas:
        Color:
            rgba: 1,0,0,1
        Rectangle:
            size: self.size
            pos: self.pos

<Body>:
    canvas:
        Color:
            rgba: 0,1,0,1
        Rectangle:
            size: self.size
            pos: self.pos

<Fruit>:
    canvas:
        Color:
            rgba: 0,0,1,1
        Ellipse:
            pos: self.pos
            size: self.size
